### ISSUE TITLE
Tag for latest version

### ISSUE THREAD

**Issue by keeba0** [criticalmaps/criticalmaps-android#133]
I see there is a 2.1.0 version in the PlayStore and I wanted to ask for an appropriate tag for that version, so that it can be published on F-Droid, too.
Thanks!

**Comment by stephanlindauer** [comment]
yep. i will publish the tag soon. i thought its probably best to give the app a testdrive on the play store before releasing on f-droid.

**Comment by stephanlindauer** [comment]
done

**Comment by keeba0** [comment]
Nice! But one more thing: You may wonder why there isn't a new build on F-Droid. It is because you forgot to increase the versionCode since 2.0.6. And your versionName should correspond with the tag name.

**Comment by stephanlindauer** [comment]
you're right. sorry. it's fixed now.
